initial version of teddies_shop based on wx_pay
lewagon/teddies_shop-wx_pay pull request #1
Opened 2017-03-20 15:09 UTC by Eric-Guo

2017-03-27 10:49 UTC, ssaunier requested changes
Overall, LGTM+ - Have some questions on gem versions

2017-03-27 10:49 UTC, ssaunier commented on Gemfile
> +gem 'rails', '~> 5.1.0.beta1'
Is there any reason you need to use the beta version?

2017-03-27 10:49 UTC, ssaunier commented on Gemfile
> +gem 'wx_pay', git: 'git@github.com:Eric-Guo/wx_pay.git', branch: :master
Why do you need a specific version of the gem?

2017-03-27 10:49 UTC, ssaunier commented on .ruby-version
> +2.4.0
We are still using `2.3.3` at Le Wagon.

2017-03-27 10:49 UTC, ssaunier commented on app/assets/config/manifest.js
> +//= link_tree ../images
I think this is something brought by Rails 5.1

Again, we'll wait the stable version to be released before teaching it.

2017-03-27 15:32 UTC, Eric-Guo commented on app/assets/config/manifest.js
> +//= link_tree ../images
Now downgrade to Rails 5.0.2 and ruby version is also not binding to 2.4, I do the pay testing and all works as expected.

For manifest.js, it still can be exist even in 5.0.2, so I still prefer keep it to make further upgrade easier.

2017-03-28 23:43 UTC, ssaunier commented
👍

2017-03-28 23:43 UTC, merged